In [13]:
import pandas as pd
import numpy as np
import seaborn as sns

In [14]:
import pandas as pd

# Caminho para o arquivo .xlsx
caminho_arquivo = '../Dados/IPMA/NovasAmostras/Resposta_P_T_HR_dd_ff_horarios Lx_EMA579.xlsx'

# Lê o arquivo Excel
df = pd.read_excel(
    caminho_arquivo,
    sheet_name='Lisboa_Gago Coutinho_EMA',
    skiprows=0, 
    engine='openpyxl'
)

print(df.head())

    ANO  MÊS  DIA  HORA   P_EST  T_MED  HR_MED  DD_MED  FF_MED
0  2023    8    1     0  1008.6   20.7      79     355     4.3
1  2023    8    1     1  1008.2   20.8      80     352     3.5
2  2023    8    1     2  1008.0   20.5      85     348     3.7
3  2023    8    1     3  1007.6   19.8      91     352     3.4
4  2023    8    1     4  1007.3   20.0      86     358     2.5

In [15]:
for col in ['P_EST', 'T_MED', 'FF_MED']:
    df[col] = df[col].astype(str).str.replace(',', '.').astype(float)

In [16]:
# Supondo que o DataFrame se chama df

# Primeiro, criamos a nova coluna 'DATA_HORA' com strings formatadas
df['DATA_HORA'] = df.apply(
    lambda row: f"{int(row['ANO'])}-{int(row['MÊS']):02d}-{int(row['DIA']):02d} {int(row['HORA']):02d}:00:00",
    axis=1
)

# (Opcional) Converte para datetime do pandas
df['DATA_HORA'] = pd.to_datetime(df['DATA_HORA'], format='%Y-%m-%d %H:%M:%S')

# (Opcional) Reorganiza as colunas colocando 'DATA_HORA' na frente
cols = ['DATA_HORA'] + [col for col in df.columns if col not in ['ANO', 'MÊS', 'DIA', 'HORA', 'DATA_HORA']]
df = df[cols]

print(df.head())

            DATA_HORA   P_EST  T_MED  HR_MED  DD_MED  FF_MED
0 2023-08-01 00:00:00  1008.6   20.7      79     355     4.3
1 2023-08-01 01:00:00  1008.2   20.8      80     352     3.5
2 2023-08-01 02:00:00  1008.0   20.5      85     348     3.7
3 2023-08-01 03:00:00  1007.6   19.8      91     352     3.4
4 2023-08-01 04:00:00  1007.3   20.0      86     358     2.5

In [17]:
conn_file = "./dados_combinados_CONNECTLIS.csv"

# Carregar dados processados
file_path_conn = './dados_combinados_CONNECTLIS.csv'
df_con = pd.read_csv(file_path_conn, delimiter=',')  # Ajuste o caminho conforme necessário

df_con.head()

,Pairing,NATIO,IN_FLT_NR,IN_BOARD_PNT,IN_OFF_PNT,IN_STD,OUT_STD,OUT_FLT_NR,OUT_BOARD_PNT,OUT_OFF_PNT,MISCONN,SUCCESS_TRANSF,PAX TRANSF,CONNECTIVITY
0,TP 1243 PRG - IAD TP 0233,AFG,TP 1243,PRG,LIS,2024-02-29 00:00:00,2024-03-01 00:00:00,TP 0233,LIS,IAD,0,1,1,"100,00%"
1,LH 1166 FRA - LAD TP 0287,AGO,LH 1166,FRA,LIS,2024-03-01 00:00:00,2024-03-01 00:00:00,TP 0287,LIS,LAD,0,1,1,"100,00%"
2,TP 0204 EWR - LAD TP 0287,AGO,TP 0204,EWR,LIS,2024-03-01 00:00:00,2024-03-01 00:00:00,TP 0287,LIS,LAD,0,2,2,"100,00%"
3,TP 0232 IAD - LAD TP 0287,AGO,TP 0232,IAD,LIS,2024-02-29 00:00:00,2024-03-01 00:00:00,TP 0287,LIS,LAD,0,1,1,"100,00%"
4,TP 0288 LAD - ORY TP 0438,AGO,TP 0288,LAD,LIS,2024-03-01 00:00:00,2024-03-01 00:00:00,TP 0438,LIS,ORY,0,1,1,"100,00%"

In [18]:
arr_file = "./dados_combinados_ARRLIS.csv"

# Carregar dados processados
file_path_arr = './dados_combinados_ARRLIS.csv'
df_arr = pd.read_csv(file_path_arr, delimiter=',')  # Ajuste o caminho conforme necessário

# Verificar as primeiras linhas do DataFrame após a alteração
df_arr.head()

,Flight Nr_arr,Dep Airport_arr,STAND_DEP_arr,Arr Airport_arr,COD GATE ARR_arr,STAND_ARR_arr,SCHD_DEP_DT_arr,SCHD_DEP_TM_arr,ACT_DEP_DT_arr,ACT_DEP_TM_arr,SCHD_ARR_DT_arr,SCHD_ARR_TM_arr,ACT_ARR_DT_arr,ACT_ARR_TM_arr,Sales Capacity_arr,NR_PAX_arr,Soma de ARR_DLY_TM_SCHD_ACT_arr
0,TP 0008,NAT,.,LIS,N,803,2023-10-01 00:00:00,01:15,2023-10-01 00:00:00,01:01,2023-10-01 00:00:00,08:25,2023-10-01 00:00:00,07:51,168,171,-34
1,TP 0012,REC,.,LIS,N,404,2023-10-01 00:00:00,01:20,2023-10-01 00:00:00,01:45,2023-10-01 00:00:00,08:50,2023-10-01 00:00:00,08:47,269,260,-3
2,TP 0022,SSA,.,LIS,43,143,2023-10-01 00:00:00,01:55,2023-10-01 00:00:00,02:08,2023-10-01 00:00:00,10:10,2023-10-01 00:00:00,10:01,296,265,-9
3,TP 0036,FOR,.,LIS,N,602,2023-10-01 00:00:00,01:40,2023-10-01 00:00:00,01:37,2023-10-01 00:00:00,08:50,2023-10-01 00:00:00,08:34,376,314,-16
4,TP 0048,BEL,.,LIS,N,607,2023-10-01 00:00:00,02:35,2023-10-01 00:00:00,02:22,2023-10-01 00:00:00,10:15,2023-10-01 00:00:00,09:42,156,145,-33

In [19]:
# --- Configuration ---
# File paths (ASSUMES files are in the same directory as the script)
dep_file = "./dados_combinados_DEPLIS.csv"

# Carregar dados processados
file_path_dep = './dados_combinados_DEPLIS.csv'
df_dep = pd.read_csv(file_path_dep, delimiter=',')  # Ajuste o caminho conforme necessário

# Verificar as primeiras linhas do DataFrame após a alteração
df_dep.head()

,Flight Nr_dep,Dep Airport_dep,COD GATE DEP_dep,STAND_DEP_dep,Arr Airport_dep,STAND_ARR_dep,SCHD_DEP_DT_dep,SCHD_DEP_TM_dep,ACT_DEP_DT_dep,ACT_DEP_TM_dep,SCHD_ARR_DT_dep,SCHD_ARR_TM_dep,ACT_ARR_DT_dep,ACT_ARR_TM_dep,Sales Capacity_dep,NR_PAX_dep
0,TP 0009,LIS,45B,414,NAT,.,2024-03-01 00:00:00,17:10,2024-03-01 00:00:00,17:24,2024-03-02 00:00:00,00:45,2024-03-02 00:00:00,01:09,168,128
1,TP 0011,LIS,43,143,REC,.,2024-03-01 00:00:00,17:00,2024-03-01 00:00:00,17:13,2024-03-02 00:00:00,00:50,2024-03-02 00:00:00,01:12,298,261
2,TP 0029,LIS,42,142,SSA,.,2024-03-01 00:00:00,16:55,2024-03-01 00:00:00,17:04,2024-03-02 00:00:00,01:40,2024-03-02 00:00:00,01:43,298,227
3,TP 0035,LIS,45A,425,FOR,.,2024-03-01 00:00:00,17:00,2024-03-01 00:00:00,17:47,2024-03-02 00:00:00,00:45,2024-03-02 00:00:00,01:17,269,188
4,TP 0057,LIS,42,142,BSB,.,2024-03-01 00:00:00,09:55,2024-03-01 00:00:00,10:10,2024-03-01 00:00:00,19:40,2024-03-01 00:00:00,19:32,298,237

In [20]:
# Função para verificar valores nulos por coluna em qualquer DataFrame
def verificar_nulos(df, nome_df):
    print(f"\nDados omissos em {nome_df}:")
    print(df.isna().sum().sort_values(ascending=False))

# Verificando para os três DataFrames
verificar_nulos(df_arr, "ARRLIS")
verificar_nulos(df_con, "CONNLIS")
verificar_nulos(df_dep, "DEPLIS")

Dados omissos em ARRLIS:
Flight Nr_arr                      0
Dep Airport_arr                    0
STAND_DEP_arr                      0
Arr Airport_arr                    0
COD GATE ARR_arr                   0
STAND_ARR_arr                      0
SCHD_DEP_DT_arr                    0
SCHD_DEP_TM_arr                    0
ACT_DEP_DT_arr                     0
ACT_DEP_TM_arr                     0
SCHD_ARR_DT_arr                    0
SCHD_ARR_TM_arr                    0
ACT_ARR_DT_arr                     0
ACT_ARR_TM_arr                     0
Sales Capacity_arr                 0
NR_PAX_arr                         0
Soma de ARR_DLY_TM_SCHD_ACT_arr    0
dtype: int64

Dados omissos em CONNLIS:
Pairing           0
NATIO             0
IN_FLT_NR         0
IN_BOARD_PNT      0
IN_OFF_PNT        0
IN_STD            0
OUT_STD           0
OUT_FLT_NR        0
OUT_BOARD_PNT     0
OUT_OFF_PNT       0
MISCONN           0
SUCCESS_TRANSF    0
PAX TRANSF        0
CONNECTIVITY      0
dtype: int64

Dados omissos em DEPLIS:
Flight Nr_dep         0
Dep Airport_dep       0
COD GATE DEP_dep      0
STAND_DEP_dep         0
Arr Airport_dep       0
STAND_ARR_dep         0
SCHD_DEP_DT_dep       0
SCHD_DEP_TM_dep       0
ACT_DEP_DT_dep        0
ACT_DEP_TM_dep        0
SCHD_ARR_DT_dep       0
SCHD_ARR_TM_dep       0
ACT_ARR_DT_dep        0
ACT_ARR_TM_dep        0
Sales Capacity_dep    0
NR_PAX_dep            0
dtype: int64

In [ ]:
import pandas as pd
import numpy as np
import time
import os
from sklearn.model_selection import train_test_split # Used for the 80/20 split logic

# --- Configuration ---
# File paths (ASSUMES files are in the same directory as the script)
conn_file = "./dados_combinados_CONNECTLIS.csv"
arr_file = "./dados_combinados_ARRLIS.csv"
dep_file = "./dados_combinados_DEPLIS.csv"


# Output files
output_file = "./dados_VOO_processados.csv"

# Columns to keep (Based on previous user input and keys)
# Ensure key columns and essential columns for checking merge success are included


cols_to_keep_arr = [
    "Flight Nr_arr",
    "Dep Airport_arr",
    "STAND_DEP_arr",
    "Arr Airport_arr",
    "COD GATE ARR_arr",
    "STAND_ARR_arr",
    "SCHD_DEP_DT_arr",
    "SCHD_DEP_TM_arr",
    "ACT_DEP_DT_arr",
    "ACT_DEP_TM_arr",
    "SCHD_ARR_DT_arr",
    "SCHD_ARR_TM_arr",
    "ACT_ARR_DT_arr",
    "ACT_ARR_TM_arr",
    "Sales Capacity_arr",
    "NR_PAX_arr",
    "Soma de ARR_DLY_TM_SCHD_ACT_arr"
]
cols_to_keep_con = [
    "Pairing",
    "NATIO",
    "IN_FLT_NR",
    "IN_BOARD_PNT",
    "IN_OFF_PNT",
    "IN_STD",
    "OUT_STD",
    "OUT_FLT_NR",
    "OUT_BOARD_PNT",
    "OUT_OFF_PNT",
    "MISCONN",
    "SUCCESS_TRANSF",
    "PAX TRANSF",
    "CONNECTIVITY"
   
]
cols_to_keep_dep = [
    "Flight Nr_dep",
    "Dep Airport_dep",
    "COD GATE DEP_dep",
    "STAND_DEP_dep",
    "Arr Airport_dep",
    "STAND_ARR_dep",
    "SCHD_DEP_DT_dep",
    "SCHD_DEP_TM_dep",
    "ACT_DEP_DT_dep",
    "ACT_DEP_TM_dep",
    "SCHD_ARR_DT_dep",
    "SCHD_ARR_TM_dep",
    "ACT_ARR_DT_dep",
    "ACT_ARR_TM_dep",
    "Sales Capacity_dep",
    "NR_PAX_dep"
]

# Target variable
target_column = "MISCONN"
expected_classes = [0, 1] # Define the valid classes for the target

# Target variable
#target_column = "CONNECTIVITY"
#treshold = 50% # Define the valid classes for the target

# Batch processing parameters
batch_size = 500000 # Adjust based on available RAM

# --- Helper Functions ---
def check_file_exists(filepath):
    if not os.path.exists(filepath):
        print(f"ERRO FATAL: Ficheiro não encontrado: {filepath}")
        return False
    return True

def load_lookup_df(filepath, cols_to_keep, key_col):
    """Loads smaller dataframes fully into memory if possible, selecting columns and setting index."""
    print(f"Tentando carregar ficheiro de lookup: {filepath}")
    if not check_file_exists(filepath):
        return None
    try:
        if key_col not in cols_to_keep:
             cols_to_keep = cols_to_keep + [key_col]
        df = pd.read_csv(filepath, usecols=cols_to_keep, low_memory=False)
        df[key_col] = df[key_col].astype(str).str.strip()
        df = df.drop_duplicates(subset=[key_col], keep='first') 
        df = df.set_index(key_col)
        print(f"  - Carregado com sucesso. Shape: {df.shape}")
        return df
    except Exception as e:
        print(f"  - ERRO ao carregar {filepath}: {e}")
        return None

# --- Main Preprocessing and Split Pipeline ---
def run_preprocess_split():
    start_time = time.time()

    # 1. Check for essential input files
    if not all(check_file_exists(f) for f in [conn_file, arr_file, dep_file]):
        print("\nPipeline não iniciado devido a ficheiros de entrada em falta.")
        return
    
    # 2. Load smaller lookup tables (ARR and DEP)
    df_arr_lookup = load_lookup_df(arr_file, cols_to_keep_arr, "Flight Nr_arr")
    df_dep_lookup = load_lookup_df(dep_file, cols_to_keep_dep, "Flight Nr_dep")

    if df_arr_lookup is None or df_dep_lookup is None:
        print("ERRO: Falha ao carregar ficheiros ARR ou DEP. Abortando.")
        return
        
    # Identify check columns
    original_check_col_arr = next((col for col in df_arr_lookup.columns if col != "Flight Nr_arr"), None)
    original_check_col_dep = next((col for col in df_dep_lookup.columns if col != "Flight Nr_dep"), None)
    
    if not original_check_col_arr or not original_check_col_dep:
        print("ERRO: Não foi possível identificar colunas de verificação nos dataframes ARR/DEP.")
        return

    # 3. Initialize output files (write header)
    first_write = True
    header_written = False
    final_columns_list = [] # To store the final column names for the header

    total_rows_processed = 0
    total_rows_valid = 0
    total_rows = 0
    total_rows_dropped_merge = 0
    total_rows_dropped_target = 0

    print(f"\nIniciando pré-processamento de {conn_file}...")
    print(f"Tamanho do batch: {batch_size}")
    print(f"Ficheiro de output: {output_file}")

    try:
        # 4. Process CONN file in chunks
        for i, df_con_chunk in enumerate(pd.read_csv(conn_file, usecols=cols_to_keep_con, chunksize=batch_size, low_memory=False)):
            batch_start_time = time.time()
            print(f"\n--- Processando Batch {i+1} --- Shape: {df_con_chunk.shape}")
            rows_in_batch = len(df_con_chunk)
            total_rows_processed += rows_in_batch

            # Prepare keys
            df_con_chunk["IN_FLT_NR"] = df_con_chunk["IN_FLT_NR"].astype(str).str.strip()
            df_con_chunk["OUT_FLT_NR"] = df_con_chunk["OUT_FLT_NR"].astype(str).str.strip()                      

            # Merge
            df_merged_chunk = df_con_chunk.join(df_arr_lookup, on="IN_FLT_NR", how="left", lsuffix="_con", rsuffix="_arr")
            df_merged_chunk = df_merged_chunk.join(df_dep_lookup, on="OUT_FLT_NR", how="left", lsuffix="_con", rsuffix="_dep")
            print(f"  - Merge concluído. Shape após merges: {df_merged_chunk.shape}")

            df_merged_chunk[target_column] = pd.to_numeric(df_merged_chunk[target_column])

            # Filtrar as linhas inválidas
            #invalid_target_rows = df_merged_chunk[                
            #    ~df_merged_chunk[target_column].isin(expected_classes)
            #]

            # Imprimir as linhas removidas
            #if not invalid_target_rows.empty:
            #    print("Linhas removidas por target inválido ou NaN:\n \n \n")
            #    print(invalid_target_rows["MISCONN"],invalid_target_rows["SUCCESS_TRANSF"],invalid_target_rows["PAX TRANSF"],invalid_target_rows["CONNECTIVITY"])

            # Drop rows without full match
            check_col_arr_final = f"{original_check_col_arr}" if f"{original_check_col_arr}" in df_merged_chunk.columns else original_check_col_arr
            check_col_dep_final = f"{original_check_col_dep}" if f"{original_check_col_dep}" in df_merged_chunk.columns else original_check_col_dep
            cols_to_check_for_na = []
            if check_col_arr_final in df_merged_chunk.columns: cols_to_check_for_na.append(check_col_arr_final)
            if check_col_dep_final in df_merged_chunk.columns: cols_to_check_for_na.append(check_col_dep_final)
            
            initial_rows_merge = len(df_merged_chunk)
            if cols_to_check_for_na:
                df_merged_chunk = df_merged_chunk.dropna(subset=cols_to_check_for_na)
            rows_after_drop_merge = len(df_merged_chunk)
            rows_dropped_merge_batch = initial_rows_merge - rows_after_drop_merge
            total_rows_dropped_merge += rows_dropped_merge_batch
            print(f"  - Linhas removidas por falta de correspondência no merge: {rows_dropped_merge_batch}")
            
       
            # Validate and Filter Target Column
            initial_rows_target = len(df_merged_chunk)    
            df_merged_chunk = df_merged_chunk.dropna(subset=[target_column])
            if not df_merged_chunk.empty:
                 df_merged_chunk[target_column] = df_merged_chunk[target_column].astype(int)
            rows_after_target_filter = len(df_merged_chunk)
            rows_dropped_target_batch = initial_rows_target - rows_after_target_filter
            total_rows_dropped_target += rows_dropped_target_batch
            print(f"  - Linhas removidas por target inválido/NaN: {rows_dropped_target_batch}")        
               
    
            # Select final columns (excluding leakage features)
            if not header_written: # Determine final columns only once
                all_cols = df_merged_chunk.columns.tolist()
                final_columns_list = all_cols
                print(f"  - Colunas finais definidas: {final_columns_list}")
            
            if not final_columns_list:
                print("ERRO CRÍTICO: Não foi possível determinar a lista final de colunas. Abortando.")
                return
                
            df_processed_chunk = df_merged_chunk[final_columns_list]        

            # 6. Append to output files
            # Write header only if it's the very first write operation to either file
            write_header = first_write and not header_written            
            
            if not df_processed_chunk.empty:
                df_processed_chunk.to_csv(output_file, mode='a', header=write_header, index=False)
                if write_header:
                     first_write = False
                     header_written = True # Mark header as written
                total_rows += len(df_processed_chunk)                  
                
            batch_time = time.time() - batch_start_time
            print(f"  - Batch {i+1} processado e dividido em {batch_time:.2f} segundos.")
            
    except Exception as e:
        print(f"\nERRO INESPERADO durante o pré-processamento e divisão: {e}")
        import traceback
        traceback.print_exc()
    finally:
        end_time = time.time()
        total_time = end_time - start_time
        print(f"\n--- Pré-processamento e Divisão Concluídos ---")
        print(f"Total de linhas do ficheiro CONN processadas: {total_rows_processed}")
        print(f"Total de linhas removidas por falha no merge: {total_rows_dropped_merge} ({total_rows_dropped_merge/total_rows_processed:.2%} do total processado)")
        print(f"Total de linhas removidas por target inválido/NaN: {total_rows_dropped_target} ({total_rows_dropped_target/total_rows_processed:.2%} do total processado)")
        print(f"Total de linhas válidas (após merge e filtro): {total_rows_valid}")
        print(f"Total de linhas escritas em {output_file}: {total_rows}")
        print(f"Tempo total de execução: {total_time:.2f} segundos.")

# --- Executar Pipeline ---
if __name__ == "__main__":
    # Remove output files if they exist to start fresh
    if os.path.exists(output_file):
        os.remove(output_file)
        print(f"Ficheiro de merge anterior removido: {output_file}")
        
    run_preprocess_split()

Ficheiro de merge anterior removido: ./dados_VOO_processados.csv
Tentando carregar ficheiro de lookup: ./dados_combinados_ARRLIS.csv
  - Carregado com sucesso. Shape: (508, 16)
Tentando carregar ficheiro de lookup: ./dados_combinados_DEPLIS.csv
  - Carregado com sucesso. Shape: (464, 15)

Iniciando pré-processamento de ./dados_combinados_CONNECTLIS.csv...
Tamanho do batch: 500000
Ficheiro de output: ./dados_VOO_processados.csv

--- Processando Batch 1 --- Shape: (500000, 14)
  - Merge concluído. Shape após merges: (500000, 45)
  - Linhas removidas por falta de correspondência no merge: 29430
  - Linhas removidas por target inválido/NaN: 0
  - Colunas finais definidas: ['Pairing', 'NATIO', 'IN_FLT_NR', 'IN_BOARD_PNT', 'IN_OFF_PNT', 'IN_STD', 'OUT_STD', 'OUT_FLT_NR', 'OUT_BOARD_PNT', 'OUT_OFF_PNT', 'MISCONN', 'SUCCESS_TRANSF', 'PAX TRANSF', 'CONNECTIVITY', 'Dep Airport_arr', 'STAND_DEP_arr', 'Arr Airport_arr', 'COD GATE ARR_arr', 'STAND_ARR_arr', 'SCHD_DEP_DT_arr', 'SCHD_DEP_TM_arr', 'ACT_DEP_DT_arr', 'ACT_DEP_TM_arr', 'SCHD_ARR_DT_arr', 'SCHD_ARR_TM_arr', 'ACT_ARR_DT_arr', 'ACT_ARR_TM_arr', 'Sales Capacity_arr', 'NR_PAX_arr', 'Soma de ARR_DLY_TM_SCHD_ACT_arr', 'Dep Airport_dep', 'COD GATE DEP_dep', 'STAND_DEP_dep', 'Arr Airport_dep', 'STAND_ARR_dep', 'SCHD_DEP_DT_dep', 'SCHD_DEP_TM_dep', 'ACT_DEP_DT_dep', 'ACT_DEP_TM_dep', 'SCHD_ARR_DT_dep', 'SCHD_ARR_TM_dep', 'ACT_ARR_DT_dep', 'ACT_ARR_TM_dep', 'Sales Capacity_dep', 'NR_PAX_dep']
  - Batch 1 processado e dividido em 8.36 segundos.

--- Processando Batch 2 --- Shape: (500000, 14)
  - Merge concluído. Shape após merges: (500000, 45)
  - Linhas removidas por falta de correspondência no merge: 30377
  - Linhas removidas por target inválido/NaN: 0
  - Batch 2 processado e dividido em 8.88 segundos.

--- Processando Batch 3 --- Shape: (500000, 14)
  - Merge concluído. Shape após merges: (500000, 45)
  - Linhas removidas por falta de correspondência no merge: 28802
  - Linhas removidas por target inválido/NaN: 0
  - Batch 3 processado e dividido em 11.23 segundos.

--- Processando Batch 4 --- Shape: (68777, 14)
  - Merge concluído. Shape após merges: (68777, 45)
  - Linhas removidas por falta de correspondência no merge: 3282
  - Linhas removidas por target inválido/NaN: 0
  - Batch 4 processado e dividido em 1.82 segundos.

--- Pré-processamento e Divisão Concluídos ---
Total de linhas do ficheiro CONN processadas: 1568777
Total de linhas removidas por falha no merge: 91891 (5.86% do total processado)
Total de linhas removidas por target inválido/NaN: 0 (0.00% do total processado)
Total de linhas válidas (após merge e filtro): 0
Total de linhas escritas em ./dados_VOO_processados.csv: 1476886
Tempo total de execução: 33.86 segundos.

In [31]:
# Função para verificar valores nulos por coluna em qualquer DataFrame

df = pd.read_csv(output_file, delimiter=',')

def verificar_nulos(df, nome_df):
    print(f"\nDados omissos em {nome_df}:")
    print(df.isna().sum().sort_values(ascending=False))

# Verificando para os três DataFrames
verificar_nulos(df,"merge")

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\2806828036.py:3: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(output_file, delimiter=',')

Dados omissos em merge:
Pairing                            0
NATIO                              0
IN_FLT_NR                          0
IN_BOARD_PNT                       0
IN_OFF_PNT                         0
IN_STD                             0
OUT_STD                            0
OUT_FLT_NR                         0
OUT_BOARD_PNT                      0
OUT_OFF_PNT                        0
MISCONN                            0
SUCCESS_TRANSF                     0
PAX TRANSF                         0
CONNECTIVITY                       0
Dep Airport_arr                    0
STAND_DEP_arr                      0
Arr Airport_arr                    0
COD GATE ARR_arr                   0
STAND_ARR_arr                      0
SCHD_DEP_DT_arr                    0
SCHD_DEP_TM_arr                    0
ACT_DEP_DT_arr                     0
ACT_DEP_TM_arr                     0
SCHD_ARR_DT_arr                    0
SCHD_ARR_TM_arr                    0
ACT_ARR_DT_arr                     0
ACT_ARR_TM_arr                     0
Sales Capacity_arr                 0
NR_PAX_arr                         0
Soma de ARR_DLY_TM_SCHD_ACT_arr    0
Dep Airport_dep                    0
COD GATE DEP_dep                   0
STAND_DEP_dep                      0
Arr Airport_dep                    0
STAND_ARR_dep                      0
SCHD_DEP_DT_dep                    0
SCHD_DEP_TM_dep                    0
ACT_DEP_DT_dep                     0
ACT_DEP_TM_dep                     0
SCHD_ARR_DT_dep                    0
SCHD_ARR_TM_dep                    0
ACT_ARR_DT_dep                     0
ACT_ARR_TM_dep                     0
Sales Capacity_dep                 0
NR_PAX_dep                         0
dtype: int64

Fazer merge do dataset IPMA de acordo com a data das medições. Chave: DATE_TIME

In [35]:
import pandas as pdcol_nameDATA_HORA
import numpy as np
import os
import time

# --- Configuração ---
# Caminhos dos ficheiros
weather_file = "./metereologia.csv"
flight_file = "./dados_VOO_processados.csv"
merge_ipma = "./dados_VOO_IPMA.csv"

# Coluna de data-hora e colunas meteorológicas
weather_time_col = "DATA_HORA"
weather_cols = ["DATA_HORA", "P_EST", "T_MED", "HR_MED", "DD_MED", "FF_MED"]

# Parâmetros de processamento em lotes
batch_size = 100000  # Ajustar com base na RAM disponível

# --- Funções Auxiliares ---
def format_datetime(df, col_name):
    """Formata uma coluna de data-hora para o formato padrão."""
    try:
        df[col_name] = pd.to_datetime(df[col_name])
        return True
    except Exception as e:
        print(f"ERRO ao formatar coluna {col_name}: {e}")
        return False

def extract_date_only(df, col_name, new_col_name=None):
    """Extrai apenas a data (sem hora) de uma coluna de data-hora."""      
    try:
        df[new_col_name] = df[col_name].dt.floor('H')
        return True
    except Exception as e:
        print(f"ERRO ao extrair data de {col_name}: {e}")
        return False

# --- Função Principal de Fusão ---
def merge_flight_weather_data():
    start_time = time.time()
    
    # 1. Verificar se os ficheiros existem
    if not all(check_file_exists(f) for f in [weather_file, flight_file]):
        print("\nProcesso não iniciado devido a ficheiros em falta.")
        return
    
    # 2. Carregar dados meteorológicos (assumindo que cabem na memória)
    print(f"\nA carregar dados meteorológicos de {weather_file}...")
    try:
        df_weather = pd.read_csv(weather_file)
        print(f"  - Dados meteorológicos carregados. Shape: {df_weather.shape}")
        
        # Formatar coluna de data-hora
        if not format_datetime(df_weather, weather_time_col):
            print("ERRO: Falha ao formatar coluna de data-hora nos dados meteorológicos.")
            return
        
        # Extrair apenas a data (sem hora) para correspondência aproximada
        if not extract_date_only(df_weather, weather_time_col, "DATA_APENAS"):
            print("ERRO: Falha ao extrair data dos dados meteorológicos.")
            return
            
        print("  - Coluna de data-hora formatada e data extraída para correspondência aproximada.")
        
    except Exception as e:
        print(f"ERRO ao carregar dados meteorológicos: {e}")
        return
    
    # 3. Inicializar ficheiro de saída (escrever cabeçalho)
    header_written = False
    total_rows_processed = 0
    total_rows_merged = 0
    total_rows_with_weather = 0
    
    print(f"\nIniciando processamento de {flight_file} em lotes...")
    
    try:
        # 4. Processar ficheiro de voos em lotes
        for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
            batch_start_time = time.time()
            print(f"\n--- Processando Lote {i+1} --- Shape: {df_flight_chunk.shape}")
            rows_in_batch = len(df_flight_chunk)
            total_rows_processed += rows_in_batch
            
            # Identificar todas as colunas de data-hora no ficheiro de voos
            date_cols = [col for col in df_flight_chunk.columns if 
                         any(substr in col.lower() for substr in ['dt', 'date', 'hora', 'time', 'std'])]
            
            print(f"  - Colunas de data-hora identificadas: {date_cols}")
            
            # Usar ACT_ARR_DT_arr como coluna principal para correspondência
            date_col_to_use = "ACT_ARR_DT_arr"
            
            if date_col_to_use in df_flight_chunk.columns:
                print(f"  - Usando coluna {date_col_to_use} para correspondência.")
                
                # Formatar a coluna de data-hora
                if not format_datetime(df_flight_chunk, date_col_to_use):
                    print(f"ERRO: Falha ao formatar coluna {date_col_to_use}.")
                    continue
                
                # Extrair apenas a data (sem hora) para correspondência aproximada
                if not extract_date_only(df_flight_chunk, date_col_to_use, "DATA_APENAS"):
                    print(f"ERRO: Falha ao extrair data da coluna {date_col_to_use}.")
                    continue
                
                # Realizar a fusão com os dados meteorológicos usando apenas a data
                merged_chunk = pd.merge(
                    df_flight_chunk,
                    df_weather,
                    left_on="DATA_APENAS",
                    right_on="DATA_APENAS",
                    how='left'
                )
                
                # Remover a coluna auxiliar de data
                merged_chunk.drop("DATA_APENAS", axis=1, inplace=True)
                
                print(f"  - Fusão concluída. Shape após fusão: {merged_chunk.shape}")
                
                # Verificar se houve correspondências
                matched_rows = merged_chunk[~merged_chunk[weather_cols[1]].isna()].shape[0]
                total_rows_with_weather += matched_rows
                print(f"  - Linhas com correspondência meteorológica: {matched_rows} de {len(merged_chunk)} ({matched_rows/len(merged_chunk)*100:.2f}%)")
                
                # Escrever no ficheiro de saída
                merged_chunk.to_csv(merge_ipma, mode='a', header=not header_written, index=False)
                if not header_written:
                    header_written = True
                
                total_rows_merged += len(merged_chunk)
                
            else:
                print(f"AVISO: Coluna {date_col_to_use} não encontrada no lote atual.")
            
            batch_time = time.time() - batch_start_time
            print(f"  - Lote {i+1} processado em {batch_time:.2f} segundos.")
            
    except Exception as e:
        print(f"\nERRO INESPERADO durante o processamento: {e}")
        import traceback
        traceback.print_exc()
    finally:
        end_time = time.time()
        total_time = end_time - start_time
        print(f"\n--- Processamento Concluído ---")
        print(f"Total de linhas processadas: {total_rows_processed}")
        print(f"Total de linhas após fusão: {total_rows_merged}")
        print(f"Total de linhas com dados meteorológicos: {total_rows_with_weather} ({total_rows_with_weather/total_rows_merged*100:.2f}% do total)")
        print(f"Ficheiro de saída: {merge_ipma}")
        print(f"Tempo total de execução: {total_time:.2f} segundos.")

# --- Executar Processo ---
if __name__ == "__main__":
    # Remover ficheiro de saída se existir
    if os.path.exists(merge_ipma):
        os.remove(merge_ipma)
        print(f"Ficheiro de saída anterior removido: {merge_ipma}")
        
    merge_flight_weather_data()

A carregar dados meteorológicos de ./metereologia.csv...
  - Dados meteorológicos carregados. Shape: (13200, 6)
  - Coluna de data-hora formatada e data extraída para correspondência aproximada.

Iniciando processamento de ./dados_VOO_processados.csv em lotes...

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 1 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 1 processado em 1.96 segundos.

--- Processando Lote 2 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

  - Lote 2 processado em 1.99 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 3 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 3 processado em 1.86 segundos.

--- Processando Lote 4 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

  - Lote 4 processado em 1.88 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 5 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 5 processado em 1.84 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 6 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 6 processado em 1.85 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 7 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 7 processado em 1.83 segundos.

--- Processando Lote 8 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

  - Lote 8 processado em 1.90 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 9 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 9 processado em 1.87 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 10 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 10 processado em 1.86 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 11 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 11 processado em 1.84 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 12 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 12 processado em 1.89 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 13 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 13 processado em 1.87 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 14 --- Shape: (100000, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (100000, 51)
  - Linhas com correspondência meteorológica: 100000 de 100000 (100.00%)
  - Lote 14 processado em 1.91 segundos.

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:79: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, df_flight_chunk in enumerate(pd.read_csv(flight_file, chunksize=batch_size)):
C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\1232899655.py:32: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[new_col_name] = df[col_name].dt.floor('H')

--- Processando Lote 15 --- Shape: (76886, 45)
  - Colunas de data-hora identificadas: ['IN_STD', 'OUT_STD', 'SCHD_DEP_DT_arr', 'ACT_DEP_DT_arr', 'SCHD_ARR_DT_arr', 'ACT_ARR_DT_arr', 'SCHD_DEP_DT_dep', 'ACT_DEP_DT_dep', 'SCHD_ARR_DT_dep', 'ACT_ARR_DT_dep']
  - Usando coluna ACT_ARR_DT_arr para correspondência.
  - Fusão concluída. Shape após fusão: (76886, 51)
  - Linhas com correspondência meteorológica: 76886 de 76886 (100.00%)
  - Lote 15 processado em 1.48 segundos.

--- Processamento Concluído ---
Total de linhas processadas: 1476886
Total de linhas após fusão: 1476886
Total de linhas com dados meteorológicos: 1476886 (100.00% do total)
Ficheiro de saída: ./dados_VOO_IPMA.csv
Tempo total de execução: 35.71 segundos.

In [36]:
# Função para verificar valores nulos por coluna em qualquer DataFrame

df = pd.read_csv(merge_ipma, delimiter=',')

def verificar_nulos(df, nome_df):
    print(f"\nDados omissos em {nome_df}:")
    print(df.isna().sum().sort_values(ascending=False))

# Verificando para os três DataFrames
verificar_nulos(df,"merge")

C:\Users\joaoc\AppData\Local\Temp\ipykernel_3608\202332214.py:3: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(merge_ipma, delimiter=',')

Dados omissos em merge:
Pairing                            0
NATIO                              0
IN_FLT_NR                          0
IN_BOARD_PNT                       0
IN_OFF_PNT                         0
IN_STD                             0
OUT_STD                            0
OUT_FLT_NR                         0
OUT_BOARD_PNT                      0
OUT_OFF_PNT                        0
MISCONN                            0
SUCCESS_TRANSF                     0
PAX TRANSF                         0
CONNECTIVITY                       0
Dep Airport_arr                    0
STAND_DEP_arr                      0
Arr Airport_arr                    0
COD GATE ARR_arr                   0
STAND_ARR_arr                      0
SCHD_DEP_DT_arr                    0
SCHD_DEP_TM_arr                    0
ACT_DEP_DT_arr                     0
ACT_DEP_TM_arr                     0
SCHD_ARR_DT_arr                    0
SCHD_ARR_TM_arr                    0
ACT_ARR_DT_arr                     0
ACT_ARR_TM_arr                     0
Sales Capacity_arr                 0
NR_PAX_arr                         0
Soma de ARR_DLY_TM_SCHD_ACT_arr    0
Dep Airport_dep                    0
COD GATE DEP_dep                   0
STAND_DEP_dep                      0
Arr Airport_dep                    0
STAND_ARR_dep                      0
SCHD_DEP_DT_dep                    0
SCHD_DEP_TM_dep                    0
ACT_DEP_DT_dep                     0
ACT_DEP_TM_dep                     0
SCHD_ARR_DT_dep                    0
SCHD_ARR_TM_dep                    0
ACT_ARR_DT_dep                     0
ACT_ARR_TM_dep                     0
Sales Capacity_dep                 0
NR_PAX_dep                         0
DATA_HORA                          0
P_EST                              0
T_MED                              0
HR_MED                             0
DD_MED                             0
FF_MED                             0
dtype: int64

In [ ]:
# 5. Split data into train/test for the current chunk

path = './dados_VOO_processados.csv'

# Output files
train_output_file = "./dados_processados_treino.csv"
test_output_file = "./dados_processados_teste.csv"

df = pd.read_csv(path, delimiter=',')

if not df.empty:
    # Split data (80% train, 20% test)
    df_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
    
# Remove output files if they exist to start fresh
if os.path.exists(train_output_file):
    os.remove(train_output_file)
    print(f"Ficheiro de treino anterior removido: {train_output_file}")
if os.path.exists(test_output_file):
    os.remove(test_output_file)
    print(f"Ficheiro de teste anterior removido: {test_output_file}")

# Save to files
df_train.to_csv(train_output_file, index=False)
df_test.to_csv(test_output_file, index=False)